import {useState} from 'react';
import {LockKeyhole,Mail,Mic2,ShieldCheck,ArrowRight,UserRound} from 'lucide-react';
import api from '../services/api';
import {useNavigate,Link} from 'react-router-dom';
export default function Login({onLogin}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''); const nav=useNavigate();
 const submit=async e=>{e.preventDefault();setLoading(true);setError('');try{const r=await api.post('/api/auth/login',{email,password});sessionStorage.setItem('voxminds_access_token',r.data.access_token);sessionStorage.setItem('voxminds_user',JSON.stringify(r.data.user));onLogin(r.data.user);nav(r.data.user.role==='admin'?'/admin':'/dashboard');}catch(err){setError(err.response?.data?.detail||'Unable to sign in. Check your credentials.')}finally{setLoading(false)}};
 return <div className='login-page'><div className='login-visual'><div className='login-brand'><div className='logo'>V</div><div><b>VoxMinds</b><span>Your voice. Your skills. Your livelihood.</span></div></div><div className='login-copy'><div className='eyebrow'>PM-AJAY • LIVELIHOOD INTELLIGENCE</div><h1>Turn your skills into your next livelihood opportunity.</h1><p>Sign in to continue your personalized voice-led journey, recommendations and roadmap.</p><div className='login-points'><span><Mic2/> Voice-first assessment</span><span><UserRound/> Personal dashboard</span><span><ShieldCheck/> Secure JWT authentication</span></div></div></div><div className='login-card'><div className='mobile-logo'><div className='logo'>V</div><b>VoxMinds</b></div><div className='login-head'><span className='login-icon'><LockKeyhole size={20}/></span><div><h2>Welcome back</h2><p>Sign in securely to your account.</p></div></div><form onSubmit={submit}><label>Email address<div className='input-wrap'><Mail size={17}/><input value={email} onChange={e=>setEmail(e.target.value)} type='email' placeholder='you@example.com' required/></div></label><label>Password<div className='input-wrap'><LockKeyhole size={17}/><input value={password} onChange={e=>setPassword(e.target.value)} type='password' placeholder='••••••••' required/></div></label>{error&&<div className='auth-error'>{error}</div>}<button className='btn primary login-btn' disabled={loading}>{loading?'Signing in…':'Sign in'}<ArrowRight size={17}/></button></form><div className='register-link'>New to VoxMinds? <Link to='/register'>Create a beneficiary account</Link></div><div className='demo-login'><b>Development demo</b><span>User: user@voxminds.in / user123</span><span>Admin: admin@voxminds.in / admin123</span></div></div></div>
}
