import {useState} from 'react';
import {ArrowRight,LockKeyhole,Mail,MapPin,UserRound,ShieldCheck} from 'lucide-react';
import {Link,useNavigate} from 'react-router-dom';
import api from '../services/api';
export default function Register({onLogin}){
 const [form,setForm]=useState({name:'',email:'',password:'',age:'',language:'en',state:'Gujarat',district:'',education:'',current_livelihood:'',employment_preference:'wage'}); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const nav=useNavigate();
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 const submit=async e=>{e.preventDefault();setLoading(true);setError('');try{const r=await api.post('/api/auth/register',{...form,age:form.age?Number(form.age):null});sessionStorage.setItem('voxminds_access_token',r.data.access_token);sessionStorage.setItem('voxminds_user',JSON.stringify(r.data.user));onLogin(r.data.user);nav('/dashboard')}catch(err){setError(err.response?.data?.detail||'Registration failed. Please try again.')}finally{setLoading(false)}};
 return <div className='auth-simple'><div className='auth-card register-card'><div className='auth-brand'><div className='logo'>V</div><div><b>VoxMinds</b><span>Your livelihood guide</span></div></div><div className='login-head'><span className='login-icon'><UserRound size={20}/></span><div><h2>Create your account</h2><p>Start with a simple profile. You can complete the voice assessment later.</p></div></div><form className='register-grid' onSubmit={submit}><label>Full name<div className='input-wrap'><UserRound size={17}/><input name='name' value={form.name} onChange={change} placeholder='Your full name' required/></div></label><label>Email<div className='input-wrap'><Mail size={17}/><input name='email' type='email' value={form.email} onChange={change} placeholder='you@example.com' required/></div></label><label>Password<div className='input-wrap'><LockKeyhole size={17}/><input name='password' type='password' minLength='8' value={form.password} onChange={change} placeholder='At least 8 characters' required/></div></label><label>Age<div className='input-wrap'><input name='age' type='number' min='14' max='100' value={form.age} onChange={change} placeholder='Age'/></div></label><label>State<div className='input-wrap'><MapPin size={17}/><input name='state' value={form.state} onChange={change} placeholder='State'/></div></label><label>District<div className='input-wrap'><MapPin size={17}/><input name='district' value={form.district} onChange={change} placeholder='District'/></div></label><label>Education<div className='input-wrap'><input name='education' value={form.education} onChange={change} placeholder='e.g. 10th, 12th, ITI'/></div></label><label>Current livelihood<div className='input-wrap'><input name='current_livelihood' value={form.current_livelihood} onChange={change} placeholder='What do you do now?'/></div></label><label>Preferred language<select name='language' value={form.language} onChange={change}><option value='en'>English</option><option value='hi'>Hindi</option><option value='gu'>Gujarati</option></select></label><label>Employment goal<select name='employment_preference' value={form.employment_preference} onChange={change}><option value='wage'>Wage employment</option><option value='self_employment'>Self employment</option><option value='both'>Open to both</option></select></label>{error&&<div className='auth-error full'>{error}</div>}<button className='btn primary login-btn full' disabled={loading}>{loading?'Creating account…':'Create account'}<ArrowRight size={17}/></button></form><div className='register-security'><ShieldCheck size={16}/> Your password is securely hashed and sessions use short-lived JWT access tokens.</div><div className='register-link'>Already have an account? <Link to='/'>Sign in</Link></div></div></div>
}
